# Generated by Django 3.0.5 on 2020-04-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='rating')),
                ('classification', models.IntegerField(blank=True, choices=[(1, 'work'), (2, 'physical activity'), (3, 'recreation'), (4, 'displacement')], null=True, verbose_name='classification')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
            },
        ),
    ]
